### ISSUE TITLE
Does gaussian wavelets work for deep sky?

### ISSUE THREAD

**Issue by Counterfeiter** [AD-Vega/arif#2]
Hello,

how does the Software perform for deep sky images? Is it possible to get the speckling of the stars addressed or is it only used for planetary imaging?
Locking for a deep sky solution. The starfinder algorithmic and with the FWHM estimation are a bit unstable and parameter dependent.

Thanks
Sebastian

**Comment by exzombie** [comment]
To answer the question in the post title: yes. But considering the repository in which this was asked: no. Confused? Let me explain.

arif is a lucky imaging software, meaning it's using a technique that is meant to deal with atmospheric disturbance. It is only applicable to bright objects, like planets and stars. Deep sky objects are imaged with very long exposure times, so atmospheric disturbance is averaged out. Dealing with atmospheric disturbance for deep sky requires a telescope with adaptive optics, or going to space.

However, the question in the title of the issue asks about gaussian wavelets. Arif uses them for image quality estimation. But the same math can be used for image enhancement/sharpening, and it's definitely applicable to deep sky images. We have a tool for that, it's called `kinky` and lives in the [lycklig repository](https://github.com/AD-Vega/lycklig). Give it a go. Press the `h` key to get help. It needs some practice to get a feel for how the three parameters correlate, but results can be pretty good, depending on your image.

**Comment by exzombie** [comment]
Ah damn, I only now realised there's another question buried in there. You're looking for a replacement for FWHM as an estimator of seeing, correct? Then I suggest you try [HFD](https://en.wikipedia.org/wiki/Half_flux_diameter) instead, it is said to be more robust. I'm not familiar with ghe starfinder software you refer to, so I can't say whether it supports HFD.

**Comment by alajovic** [comment]
Hi Sebastian,

the quality estimation algorithm in arif is rather strongly biased towards planetary imaging, and I have a suspicion that it won't work as well on deep-sky images because these have quite different characteristics.

The quality estimation algorithm decomposes the image into three parts:

* high spatial frequencies (essentially noise)
* medium frequencies (sharp details in the imaged objects)
* low frequencies (larger and smooth features in the imaged objects)

The estimated image quality is the ratio between the cumulative power in the medium-frequency range and the cumulative power in the high-frequency range. So the algorithm is essentially a signal-to-noise estimator. The rationale behind it is that in planetary imaging, the noise power stays fairly constant, while the power in the medium-frequencies (details on the observed object) varies depending on the seeing. More blur due to the seeing = less power in the medium range = lower quality.

The point where this idea falls short for deep-sky images is that such images contain a lot of stars, and since stars are very sharp objects, they will likely fall into the high-frequency range. In other words, they will likely end up being counted as noise. Unfortunately, this invalidates one of the basic assumptions of the quality estimator, and I'm suspecting that the results will not be... stellar (pun intended). However, if you decide to give it a go nevertheless, I'd be happy to hear about your findings.

**Comment by Counterfeiter** [comment]
Thank you both for the explanation. I get it how your estimation works. I think for deep sky with stars the HFD and FWHM solutions are the most advantaged. Also Guiding Software does it really perfectly to track on or more stars and his parameters. But its not so easy to write a peace of code that make a fast assumption about the current quality of the frame to the next frame  (maybe shifted one), without less or no manual controls for the user.

Thanks 
Sebastian
